import { Pill, Stethoscope, AlertTriangle, UserRound, Layers, Boxes, Percent } from 'lucide-react'
import { formatDate } from '../utils/formatDate'
import { formatCurrency } from '../utils/formatCurrency'

const MUC_DO_LABEL = {
  CANH_BAO: 'Cảnh báo',
  TU_CHOI: 'Từ chối',
  NGHIEM_TRONG: 'Nghiêm trọng',
}

export const CATALOG_CONFIGS = {
  drug: {
    icon: Pill,
    title: 'Danh mục thuốc',
    subtitle: 'Danh mục thuốc bệnh viện dùng để đối chiếu mã chi phí trong hồ sơ giám định XML',
    searchPlaceholder: 'Tìm theo mã thuốc hoặc tên thuốc...',
    acceptFileTypes: '.xlsx,.xls,.csv',
    columns: [
      { key: 'maThuoc', header: 'Mã thuốc' },
      { key: 'tenHoatChat', header: 'Tên hoạt chất' },
      { key: 'tenThuoc', header: 'Tên thuốc' },
      { key: 'donViTinh', header: 'Đơn vị tính' },
      { key: 'hamLuong', header: 'Hàm lượng' },
      { key: 'duongDung', header: 'Đường dùng' },
      { key: 'maDuongDung', header: 'Mã đường dùng' },
      { key: 'dangBaoChe', header: 'Dạng bào chế' },
      { key: 'soDangKy', header: 'Số đăng ký' },
      { key: 'soLuong', header: 'Số lượng' },
      { key: 'donGia', header: 'Đơn giá', render: (row) => formatCurrency(row.donGia) },
      { key: 'donGiaBH', header: 'Đơn giá BH', render: (row) => formatCurrency(row.donGiaBH) },
      { key: 'quyCach', header: 'Quy cách' },
      { key: 'nhaSx', header: 'Nhà SX' },
      { key: 'nuocSx', header: 'Nước SX' },
      { key: 'nhaThau', header: 'Nhà thầu' },
      { key: 'ttThau', header: 'TT thầu' },
      { key: 'maCSKCB', header: 'Mã CSKCB' },
      { key: 'loaiThuoc', header: 'Loại thuốc' },
      { key: 'loaiThau', header: 'Loại thầu' },
      { key: 'htThau', header: 'HT thầu' },
    ],
    fields: [
      { key: 'maThuoc', label: 'Mã thuốc', type: 'text', required: true },
      { key: 'tenHoatChat', label: 'Tên hoạt chất', type: 'text' },
      { key: 'tenThuoc', label: 'Tên thuốc', type: 'text', required: true },
      { key: 'donViTinh', label: 'Đơn vị tính', type: 'text' },
      { key: 'hamLuong', label: 'Hàm lượng', type: 'text' },
      { key: 'duongDung', label: 'Đường dùng', type: 'text' },
      { key: 'maDuongDung', label: 'Mã đường dùng', type: 'text' },
      { key: 'dangBaoChe', label: 'Dạng bào chế', type: 'text' },
      { key: 'soDangKy', label: 'Số đăng ký', type: 'text' },
      { key: 'soLuong', label: 'Số lượng', type: 'number' },
      { key: 'donGia', label: 'Đơn giá', type: 'number' },
      { key: 'donGiaBH', label: 'Đơn giá BH', type: 'number' },
      { key: 'quyCach', label: 'Quy cách', type: 'text' },
      { key: 'nhaSx', label: 'Nhà SX', type: 'text' },
      { key: 'nuocSx', label: 'Nước SX', type: 'text' },
      { key: 'nhaThau', label: 'Nhà thầu', type: 'text' },
      { key: 'ttThau', label: 'TT thầu', type: 'text' },
      { key: 'maCSKCB', label: 'Mã CSKCB', type: 'text' },
      { key: 'loaiThuoc', label: 'Loại thuốc', type: 'text' },
      { key: 'loaiThau', label: 'Loại thầu', type: 'text' },
      { key: 'htThau', label: 'HT thầu', type: 'text' },
    ],
  },
  service: {
    icon: Stethoscope,
    title: 'Danh mục dịch vụ kỹ thuật',
    subtitle: 'Danh mục DVKT phê duyệt dùng để đối chiếu mã chi phí trong hồ sơ giám định XML',
    searchPlaceholder: 'Tìm theo mã hoặc tên dịch vụ...',
    acceptFileTypes: '.xlsx,.xls,.csv',
    columns: [
      { key: 'maTuongDuong', header: 'Mã tương đương' },
      { key: 'tenDvktPheDuyet', header: 'Tên DVKT phê duyệt' },
      { key: 'donGia', header: 'Đơn giá', render: (row) => formatCurrency(row.donGia) },
      { key: 'tuNgay', header: 'Từ ngày', render: (row) => formatDate(row.tuNgay) },
      { key: 'denNgay', header: 'Đến ngày', render: (row) => formatDate(row.denNgay) || 'Còn hiệu lực' },
    ],
    fields: [
      { key: 'maTuongDuong', label: 'Mã tương đương', type: 'text', required: true },
      { key: 'tenDvktPheDuyet', label: 'Tên DVKT phê duyệt', type: 'text', required: true },
      { key: 'donGia', label: 'Đơn giá', type: 'number' },
      { key: 'tuNgay', label: 'Từ ngày', type: 'date', required: true },
      { key: 'denNgay', label: 'Đến ngày', type: 'date' },
    ],
  },
  errorCode: {
    icon: AlertTriangle,
    title: 'Danh mục mã lỗi',
    subtitle: 'Danh mục mã lỗi/cảnh báo dùng để dự đoán khả năng bị từ chối khi gửi cổng giám định',
    searchPlaceholder: 'Tìm theo mã lỗi hoặc tên lỗi...',
    acceptFileTypes: '.xlsx,.xls,.csv',
    columns: [
      { key: 'maLoi', header: 'Mã lỗi' },
      { key: 'tenLoi', header: 'Tên lỗi' },
      { key: 'dienGiai', header: 'Diễn giải' },
      { key: 'mucDo', header: 'Mức độ', render: (row) => MUC_DO_LABEL[row.mucDo] || row.mucDo },
    ],
    fields: [
      { key: 'maLoi', label: 'Mã lỗi', type: 'text', required: true },
      { key: 'tenLoi', label: 'Tên lỗi', type: 'text', required: true },
      { key: 'dienGiai', label: 'Diễn giải', type: 'textarea' },
      {
        key: 'mucDo',
        label: 'Mức độ',
        type: 'select',
        options: Object.entries(MUC_DO_LABEL).map(([value, label]) => ({ value, label })),
      },
      { key: 'ghiChu', label: 'Ghi chú', type: 'textarea' },
    ],
  },
  doctor: {
    icon: UserRound,
    title: 'Danh mục bác sĩ',
    subtitle: 'Danh mục bác sĩ được duyệt (theo mã CCHN) dùng để đối chiếu Mã bác sĩ trong hồ sơ giám định XML',
    searchPlaceholder: 'Tìm theo họ tên hoặc mã CCHN...',
    acceptFileTypes: '.xlsx,.xls,.csv',
    columns: [
      { key: 'hoTen', header: 'Họ tên' },
      { key: 'maCCHN', header: 'Mã CCHN' },
    ],
    fields: [
      { key: 'hoTen', label: 'Họ tên', type: 'text', required: true },
      { key: 'maCCHN', label: 'Mã CCHN', type: 'text', required: true },
    ],
  },
  serviceGroup: {
    icon: Layers,
    title: 'Danh mục mã nhóm DVKT',
    subtitle: 'Mã nhóm chi phí chuẩn theo dịch vụ/thủ thuật, dùng để đối chiếu MA_NHOM trong hồ sơ giám định XML',
    searchPlaceholder: 'Tìm theo mã hoặc tên...',
    acceptFileTypes: '.xlsx,.xls,.csv',
    columns: [
      { key: 'ma', header: 'Mã' },
      { key: 'ten', header: 'Tên' },
      { key: 'loaiPTTT', header: 'Loại PTTT' },
      { key: 'maGia', header: 'Mã giá' },
      { key: 'tenGia', header: 'Tên giá' },
      { key: 'gia', header: 'Giá', render: (row) => formatCurrency(row.gia) },
      { key: 'giaSau', header: 'Giá sau', render: (row) => formatCurrency(row.giaSau) },
      { key: 'ghiChu', header: 'Ghi chú' },
      { key: 'maNhom', header: 'Mã nhóm' },
    ],
    fields: [
      { key: 'ma', label: 'Mã', type: 'text', required: true },
      { key: 'ten', label: 'Tên', type: 'text' },
      { key: 'loaiPTTT', label: 'Loại PTTT', type: 'text' },
      { key: 'maGia', label: 'Mã giá', type: 'text' },
      { key: 'tenGia', label: 'Tên giá', type: 'text' },
      { key: 'gia', label: 'Giá', type: 'number' },
      { key: 'giaSau', label: 'Giá sau', type: 'number' },
      { key: 'ghiChu', label: 'Ghi chú', type: 'textarea' },
      { key: 'maNhom', label: 'Mã nhóm', type: 'text' },
    ],
  },
  vatTu: {
    icon: Boxes,
    title: 'Danh mục vật tư y tế',
    subtitle: 'Danh mục VTYT bệnh viện dùng để đối chiếu mã vật tư trong hồ sơ giám định XML',
    searchPlaceholder: 'Tìm theo mã, tên hoặc nhóm vật tư...',
    acceptFileTypes: '.xlsx,.xls,.csv',
    columns: [
      { key: 'maVatTu', header: 'Mã vật tư' },
      { key: 'nhomVatTu', header: 'Nhóm vật tư' },
      { key: 'tenVatTu', header: 'Tên vật tư' },
      { key: 'maHieu', header: 'Mã hiệu' },
      { key: 'hangSx', header: 'Hãng SX' },
      { key: 'donViTinh', header: 'Đơn vị tính' },
      { key: 'donGia', header: 'Đơn giá', render: (row) => formatCurrency(row.donGia) },
      { key: 'donGiaBH', header: 'Đơn giá BH', render: (row) => formatCurrency(row.donGiaBH) },
      { key: 'tyLeTtBh', header: 'Tỷ lệ TT BH' },
      { key: 'soLuong', header: 'Số lượng' },
      { key: 'dinhMuc', header: 'Định mức' },
      { key: 'nhaThau', header: 'Nhà thầu' },
      { key: 'ttThau', header: 'TT thầu' },
      { key: 'maCSKCB', header: 'Mã CSKCB' },
      { key: 'loaiThau', header: 'Loại thầu' },
      { key: 'htThau', header: 'HT thầu' },
    ],
    fields: [
      { key: 'maVatTu', label: 'Mã vật tư', type: 'text', required: true },
      { key: 'nhomVatTu', label: 'Nhóm vật tư', type: 'text' },
      { key: 'tenVatTu', label: 'Tên vật tư', type: 'text', required: true },
      { key: 'maHieu', label: 'Mã hiệu', type: 'text' },
      { key: 'hangSx', label: 'Hãng SX', type: 'text' },
      { key: 'donViTinh', label: 'Đơn vị tính', type: 'text' },
      { key: 'donGia', label: 'Đơn giá', type: 'number' },
      { key: 'donGiaBH', label: 'Đơn giá BH', type: 'number' },
      { key: 'tyLeTtBh', label: 'Tỷ lệ TT BH', type: 'number' },
      { key: 'soLuong', label: 'Số lượng', type: 'number' },
      { key: 'dinhMuc', label: 'Định mức', type: 'text' },
      { key: 'nhaThau', label: 'Nhà thầu', type: 'text' },
      { key: 'ttThau', label: 'TT thầu', type: 'text' },
      { key: 'maCSKCB', label: 'Mã CSKCB', type: 'text' },
      { key: 'loaiThau', label: 'Loại thầu', type: 'text' },
      { key: 'htThau', label: 'HT thầu', type: 'text' },
    ],
  },
  benefitRate: {
    icon: Percent,
    title: 'Danh mục mức hưởng theo đối tượng',
    subtitle:
      'Bảng % chi trả BHYT theo mã đối tượng (2 ký tự đầu mã thẻ) và MA_LOAI_KCB, dùng để đối chiếu MUC_HUONG trong hồ sơ giám định XML',
    searchPlaceholder: 'Tìm theo mã đối tượng hoặc nhóm...',
    acceptFileTypes: '.xlsx,.xls,.csv',
    columns: [
      { key: 'ma', header: 'Mã đối tượng' },
      { key: 'nhom', header: 'Nhóm (MA_LOAI_KCB)' },
      { key: 'chiTraDungTuyen', header: 'Chi trả đúng tuyến (%)' },
      { key: 'chiTraTraiTuyen', header: 'Chi trả trái tuyến (%)' },
    ],
    fields: [
      { key: 'ma', label: 'Mã đối tượng', type: 'text', required: true },
      { key: 'nhom', label: 'Nhóm (MA_LOAI_KCB)', type: 'text', required: true },
      { key: 'chiTraDungTuyen', label: 'Chi trả đúng tuyến (%)', type: 'number' },
      { key: 'chiTraTraiTuyen', label: 'Chi trả trái tuyến (%)', type: 'number' },
    ],
  },
}
